[run]
commands = ["E:/daa/backup_scriptsr/backup_mssql.bat"]

[ftp]
host = "localhost"
port = 21
user = "user"
pass = "pass"
path = "backup_dir"
backup_file_name = "backup"
backup_suffix_format = ""

[[src]]
prefix = "mongodb"
path = "C:/xxx"

