[run]
commands = ["E:/path_to/backup_mongodb.bat"]

[ftp]
host = "localhost"
port = 21
user = "user"
pass = "pass"
path = "backup_dir"
backup_file_name = "backup"
backup_suffix_format = "%d-%m-%Y"

[[src]]
prefix = "mongodb"
path = "C:/path_to_add_to_archive"

[notify]
error_address = []
success_address = []

smtp_host = ""
smtp_user = ""
smtp_pass = ""
smtp_port = 25
smtp_from = ""

